spring.datasource.url=jdbc:h2:mem:learningdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true

# Geocoding URL template (name placeholder)
external.geocode.url=https://geocoding-api.open-meteo.com/v1/search?name={name}

# Weather URL template (latitude & longitude placeholders)
external.weather.url=https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true

# server port optional
# server.port=8080
